### ISSUE TITLE
from __future__ import annotations breaks schema generation

### ISSUE THREAD

**Issue by rbachleitner** [toumorokoshi/jsonschema-extractor#13]
In python3.10.4 if `from __future__ import annotations` is imported and you execute `jsonschema.extract` on an `attrs` decorated class,
all types are set to `object`.

**Comment by toumorokoshi** [comment]
Thanks for the issue! I have fix in #14. PTAL (another pair of eyes doesn't hurt), and if all looks good or if there's a lack of response and I'll get that merged in.

**Comment by toumorokoshi** [comment]
fixing in 2.0.2. Thanks!
