### ISSUE TITLE
python 3.6 issues with issubclass when using custom object annotations

### ISSUE THREAD

**Issue by jmaroeder** [toumorokoshi/jsonschema-extractor#4]
```
  File "/home/james-roeder/.../venv/lib/python3.6/site-packages/jsonschema_extractor/typing_extractor.py", line 43, in extract
    matches = t(typ)
  File "/home/james-roeder/.../venv/lib/python3.6/site-packages/jsonschema_extractor/typing_extractor.py", line 115, in _is_sequence
    return issubclass(typ, Sequence)
  File "/usr/lib/python3.6/typing.py", line 1154, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "/home/james-roeder/.../venv/lib/python3.6/abc.py", line 209, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/usr/lib/python3.6/typing.py", line 879, in __extrahook__
    if cls.__extra__ in subclass.__mro__:
AttributeError: 'function' object has no attribute '__mro__'
```

This appears to be related to the use of `issubclass` on non-classes, which can happen with custom object annotation.

I believe I have a fix, though - updating the `_is_sequence` and `_is_union` methods in `typing_extractor.py` to work off of the (undocumented) `__origin__` attribute.

```python
def _is_sequence(typ):
    origin = getattr(typ, "__origin__", None)
    return origin and issubclass(origin, Sequence)

def _is_union(typ):
    return getattr(typ, "__origin__", None) is Union
```

**Comment by toumorokoshi** [comment]
Thanks for the bug!

Currently we do a check for __origin__ if the version of python supports it (greater than 3.7.0).

That said, it sounds like some behavior around typing must've been back-ported in a newer version of 3.6. I don't believe the __origin__ will work for older versions of python (e.g. 2.7). 

I'll try expanding verified python versions in CI a bit, that should provide a clearer picture.

**Comment by toumorokoshi** [comment]
@jmaroeder I've got #5 up which resolved the issues I was able to repro in python 3.6.10. Would you mind taking a quick look?

Otherwise I'll merge and publish this tonight.

**Comment by jmaroeder** [comment]
Left a comment in the PR - thanks for acting on this so quickly!

**Comment by toumorokoshi** [comment]
Out in 0.8.2! https://pypi.org/project/jsonschema-extractor/. Give it a try.
